# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - ".github/web/"
      - "project.md5"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
      - ".github/web/"

jobs:
  build:

    runs-on: alpine
    environment: .net-test

    steps:
    - uses: actions/checkout@v4
    - name: Install .NET
      run: apk add dotnet8-sdk
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
