name: MD5 checksum
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - run: chmod 1777 md5.sh
    - name: Create md5 checksums
      run: ./md5.sh
    - name: Check the new checksums
      run: md5sum -c project.md5
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5.0.1
