name: MD5 checksum
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Create md5 checksums
      run: find -path ./.git -prune -o -type f -exec md5sum "{}" + > project.md5
    - run: cat project.md5
    - name: Check the new checksums
      run: md5sum -c project.md5
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5.0.1
